import { type HttpClient, unwrapResponse } from '../../../core/http'
import type {
  components,
  SendPayloadValue,
} from '../../../generated/openapi-types'
import type { BrewRawResponse, RequestOptions } from '../../../types'

/**
 * Un-pinned fires keep the exact wire value type (JSON-serializable only)
 * — mirrors `emails.send`'s default so the generic default cannot loosen
 * what the wire rejects (functions, undefined values silently dropped by
 * JSON.stringify).
 */
type DefaultFirePayload = {
  [key: string]: SendPayloadValue
}

/**
 * Body for `automations.triggers.fire()` plus the `triggerEventId` path
 * identity. Generic over the payload so a codebase can pin the trigger's
 * contract type (hand-written, or generated by `brew-cli types`):
 *
 * ```ts
 * import type { UserSignedUpPayload } from './brew-contracts'
 * await brew.automations.triggers.fire<UserSignedUpPayload>({
 *   triggerEventId: 'tri_signup',
 *   payload: { email, firstName }, // type-checked against the contract
 * })
 * ```
 *
 * The idempotency key is a request option
 * (`fire(input, { idempotencyKey })`), not a body field.
 */
export type FireTriggerInput<
  TPayload extends Record<string, unknown> = DefaultFirePayload,
> = {
  triggerEventId: string
} & Omit<components['schemas']['TriggerFireRequest'], 'payload'> & {
    payload: TPayload
  }

/**
 * The 202 fire body — bare in v1: `{ triggerInstanceId, triggerEventId,
 * status, automationRunIds, publishedAutomations, counts, warnings,
 * receivedAt }`. The old `{ success, code, message, details }` envelope
 * is gone.
 */
export type FireTriggerResponse = components['schemas']['TriggerFireAccepted']

/**
 * `POST /v1/automations/triggers/{triggerEventId}/fire` (scope:
 * `automations`) — fire a trigger with a `payload`; the server validates
 * it against the trigger's `payloadSchema`, upserts the derived contact,
 * and starts one run per published automation attached to the trigger.
 *
 * Returns `202` with the bare accepted body: read `automationRunIds[]`
 * and follow each run via
 * `brew.automations.runs.get(automationRunId, { include: 'logs' })`, or
 * read the whole fire back with
 * `brew.automations.triggerInstances.get(triggerInstanceId)`. Set
 * `options.idempotencyKey` on retries so a re-delivered webhook doesn't
 * double-fire — a replay answers `status: 'replayed'`.
 *
 * Pass `{ raw: true }` in `options` to receive the full
 * `BrewRawResponse<FireTriggerResponse>` instead of the unwrapped payload.
 */
export function createFireTrigger(client: HttpClient) {
  function fireTrigger<
    TPayload extends Record<string, unknown> = DefaultFirePayload,
  >(
    input: FireTriggerInput<TPayload>,
    options: RequestOptions & { readonly raw: true }
  ): Promise<BrewRawResponse<FireTriggerResponse>>
  function fireTrigger<
    TPayload extends Record<string, unknown> = DefaultFirePayload,
  >(
    input: FireTriggerInput<TPayload>,
    options?: RequestOptions
  ): Promise<FireTriggerResponse>
  async function fireTrigger(
    input: FireTriggerInput,
    options?: RequestOptions
  ): Promise<FireTriggerResponse | BrewRawResponse<FireTriggerResponse>> {
    const { triggerEventId, ...body } = input
    const response = await client.request<FireTriggerResponse>({
      method: 'POST',
      path: `/v1/automations/triggers/${encodeURIComponent(triggerEventId)}/fire`,
      body,
      ...(options ? { options } : {}),
    })
    return unwrapResponse(response, options)
  }
  return fireTrigger
}
